### ISSUE TITLE
It stops sometimes

### ISSUE THREAD

**Issue by BarukTTV** [MarcoPNS/Spotify-Stream-Widget#16] opened 2019-09-26 03:31 UTC
Hi, first of all i love it. But i had a problem while i was streaming and listening spotify, sometimes like it plays 4 or 5 songs and then stops doing it and i got to close it and re-open it. Do you know why is this problem and how i can solve it?.

**Comment by MarcoPNS** [comment] 2019-09-26 12:06
Hi @Kresteff 

Thank you for the info. I will try to reproduce this. I will also publish an update today where a logger is implemented. That could be helpful if I can't reproduce this error by myself.

**Comment by Kresteff** [comment] 2019-09-26 19:01
Thank you so much Marco!. If i have this problem again i'll re-open the comment.

**Comment by Kresteff** [comment] 2019-09-26 21:42
Hi, marco i wanted to know if you tried it and solved the problem. Just let
me know for the download. Thank you!

**Comment by MarcoPNS** [comment] 2019-09-27 08:28
I keep this issue open because it is not clear why this happens.

**Comment by MarcoPNS** [comment] 2019-09-27 13:47
Should be fixed with the new version 1.3.1.0: https://github.com/MarcoPNS/Spotify-Stream-Widget/releases/tag/1.3.1.0

**Comment by Kresteff** [comment] 2019-09-28 13:27
I have the same problem, but idk why. Like i have to close and re-open it.

**Comment by Kresteff** [comment] 2019-09-28 14:34
I have a clip of my streaming when im listening to Snuff of slipknot but it shows the previous song i heared. https://clips.twitch.tv/OpenSparklingAyeayeOhMyDog

**Comment by MarcoPNS** [comment] 2019-09-28 23:24
@Kresteff was this with the current version 1.3.1.0? If so then please post your log file from this date. You can find it in in the application folder under `/Logs/`

**Comment by Kresteff** [comment] 2019-09-29 02:06
Yes marco i was trying the last version, anyways when it's open popups a message saying there's a new version 1.3.0.0, but i already have the 1.3.1.0. There you got the log folder :)
[2019-09-27.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/3666242/2019-09-27.log)
[2019-09-28.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/3666243/2019-09-28.log)

**Comment by petersvp** [comment] 2019-10-24 00:31
I wrote another issue with the code changes I did to fix this issue.

**Comment by prolercoaster** [comment] 2019-11-23 07:22
[2019-11-20.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/3882215/2019-11-20.log)
[2019-11-21.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/3882216/2019-11-21.log)
[2019-11-22.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/3882217/2019-11-22.log)
I have been having this same issue. The widget is great when it's working, thanks!

**Comment by dsmeclipse** [comment] 2019-12-22 00:16
The errors in 13.1.0 are as follows:

2019/12/21 01:07:16 [EXCEPTION] VersionCheck_DoWork() Exception: System.InvalidCastException: Conversion from string "1.3.1.0" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   at Spotify_Stream_Widget.Settings.VersionCheck_DoWork(Object sender, DoWorkEventArgs e)

2019/12/21 02:07:44 [ERROR] Error Status: 401 Msg: The access token expired


I'm sure the first error doesn't matter. Seems that it's for a prompt or autoupdate if the application is out of date.

You issue is with the authentication with Spotify. The token expires after an hour or so. I'd recommend adding a reauthorize button. Alternatively, we as users could create a script or windows task to reauth every 30 minutes on our end (That's probably less likely!)

**Comment by MarcoPNS** [comment] 2020-06-02 23:07
Belongs to #22

**Comment by MarcoPNS** [comment] 2020-06-03 11:27
Version 1.4 is live and now referesh its access token. try it out
https://github.com/MarcoPNS/Spotify-Stream-Widget/releases/tag/1.4.0.0

**Closed by MarcoPNS** 2020-06-03 11:27 UTC
